# clears all tables before seeding
puts "cleaning tables from old records..."
GameSessionSong.destroy_all
Song.destroy_all
GenreVote.destroy_all
Genre.destroy_all

# seeding music genres
puts "seeding music genres..."
genre1 = Genre.create(name: "Pop & Dance", slug: "pop")
genre2 = Genre.create(name: "Hip-Hop & Rap", slug: "hiphop")
genre3 = Genre.create(name: "Rock", slug: "rock")
genre4 = Genre.create(name: "R&B & Soul", slug: "rb")

# Create a lookup hash
genres = {
  "Pop & Dance" => genre1.id,
  "Hip-Hop & Rap" => genre2.id,
  "Rock" => genre3.id,
  "R&B & Soul" => genre4.id
}

# seeding songs
puts "seeding songs..."
song1 = Song.create(title: "Don't Stop Believin'", artist: "Journey", youtube_url: "https://youtu.be/Pze8Dyqiky8?si=r8fr3VH4xCIt7i4_", album_url: "https://en.wikipedia.org/wiki/Don%27t_Stop_Believin%27#/media/File:Don't_Stop_Believin'.jpg", genre_id: genres["Rock"])
song2 = Song.create(title: "Snow", artist: "Red Hot Chili Peppers", youtube_url: "https://youtu.be/egpE0ysQ21Q?si=2UVQNwgRCw1hn4A2", album_url: "https://en.wikipedia.org/wiki/Snow_(Hey_Oh)#/media/File:Rhcpsnowheyoh.jpg", genre_id: genres["Rock"])
song3 = Song.create(title: "Believer", artist: "Imagine Dragons", youtube_url: "https://youtu.be/o0LydWpBQts?si=yT7lfP86_xxaBMvw", album_url: "https://en.wikipedia.org/wiki/Believer_(Imagine_Dragons_song)#/media/File:Imagine-Dragons-Believer-art.jpg", genre_id: genres["Rock"])
song4 = Song.create(title: "Fuck Off", artist: "Green Day", youtube_url: "https://youtu.be/2IATUnmIm_4?si=2zx4k3VGLtMiRFvU", album_url: "https://en.wikipedia.org/wiki/Saviors_(album)#/media/File:Green_Day_-_Saviors.png", genre_id: genres["Rock"])
song5 = Song.create(title: "Eye Of The Tiger", artist: "Survivor", youtube_url: "https://youtu.be/_qDML_BCju8?si=pVYzcmvoWmBfH64u", album_url: "https://en.wikipedia.org/wiki/Eye_of_the_Tiger#/media/File:Eye_of_the_Tiger_Survivor.jpg", genre_id: genres["Rock"])
song6 = Song.create(title: "Hold The Line", artist: "Toto", youtube_url: "https://youtu.be/7JHRNE1HeKE?si=lljM9o8wdWwNM5Fl", album_url: "https://en.wikipedia.org/wiki/Hold_the_Line#/media/File:Hold_the_Line.jpg", genre_id: genres["Rock"])
song7 = Song.create(title: "I Still Haven't Found What I'm Looking For", artist: "U2", youtube_url: "https://youtu.be/plEzQoD95c4?si=PTzLfB7ETENt0y_5", album_url: "https://en.wikipedia.org/wiki/I_Still_Haven%27t_Found_What_I%27m_Looking_For#/media/File:Still_havent_found_cover.jpg", genre_id: genres["Rock"])
song8 = Song.create(title: "To Love Somebody", artist: "Michael Bolton", youtube_url: "https://youtu.be/Dpz5kbMoKMs?si=QRoJWFBR8eH9UyzO", album_url: "https://en.wikipedia.org/wiki/To_Love_Somebody_(song)#/media/File:Tolovesomebodybolton.jpg", genre_id: genres["R&B & Soul"])
song9 = Song.create(title: "You Can Call Me Al", artist: "Paul Simon", youtube_url: "https://youtu.be/p-YhToLO-mc?si=qVhLvjrdiG-f0sVy", album_url: "https://en.wikipedia.org/wiki/You_Can_Call_Me_Al#/media/File:You_Can_Call_Me_Al.jpg", genre_id: genres["R&B & Soul"])
song10 = Song.create(title: "The Emptiness Machine", artist: "Linkin Park", youtube_url: "https://youtu.be/ugIu-niEzdU?si=1N87EF3pBAa8_d2P", album_url: "https://en.wikipedia.org/wiki/The_Emptiness_Machine#/media/File:Linkin_Park_-_%22The_Emptiness_Machine%22_cover.jpg", genre_id: genres["Rock"])
song11 = Song.create(title: "Dust in the Wind", artist: "Kansas", youtube_url: "https://youtu.be/90msAuGKbjY?si=q3x6MSs7aO6AJFqW", album_url: "https://en.wikipedia.org/wiki/Dust_in_the_Wind#/media/File:Kansas-dust-in-the-wind.jpg", genre_id: genres["Rock"])
song12 = Song.create(title: "Skyfall", artist: "Adele", youtube_url: "https://youtu.be/sZrTJesvJeo?si=YG-8-v3Oi5r2Yrhk", album_url: "https://en.wikipedia.org/wiki/Skyfall_(song)#/media/File:Skyfall_cover.png", genre_id: genres["Pop & Dance"])
song13 = Song.create(title: "Sweet Child O' Mine", artist: "Guns N' Roses", youtube_url: "https://youtu.be/qoflJn7zkFM?si=htcOKNUeIenlSjBn", album_url: "https://en.wikipedia.org/wiki/Sweet_Child_o%27_Mine#/media/File:Guns_N'_Roses_-_Sweet_Child_o'_Mine.png", genre_id: genres["Rock"])
song14 = Song.create(title: "Toxic", artist: "Britney Spears", youtube_url: "https://youtu.be/83AOwdfH1Z0?si=NMNeS130w6S8XFu2", album_url: "https://en.wikipedia.org/wiki/Toxic_(song)#/media/File:Britney_Spears_Toxic.png", genre_id: genres["Pop & Dance"])
song15 = Song.create(title: "Unstoppable", artist: "Sia", youtube_url: "https://youtu.be/5aqptmZjfb8?si=TMWqG2FfOFLYK6jJ", album_url: "https://en.wikipedia.org/wiki/Unstoppable_(Sia_song)#/media/File:Unstoppable_single_art.jpg", genre_id: genres["Pop & Dance"])
song16 = Song.create(title: "Piano Man", artist: "Billy Joel", youtube_url: "https://youtu.be/GB4YjpLk4nk?si=ZRl9Hze121RmnjuI", album_url: "https://en.wikipedia.org/wiki/Piano_Man_(song)#/media/File:Billy_Joel_Piano_Man_single.jpg", genre_id: genres["Rock"])
song17 = Song.create(title: "Mirrors", artist: "Justin Timberlake", youtube_url: "https://youtu.be/AUvwPFpCqCA?si=WJ9Eknjjj1vJWxYX", album_url: "https://en.wikipedia.org/wiki/Mirrors_(Justin_Timberlake_song)#/media/File:JTMirrorsCover.png", genre_id: genres["Pop & Dance"])
song18 = Song.create(title: "Angels Like You", artist: "Miley Cyrus", youtube_url: "https://youtu.be/DmxuL9h8foQ?si=gxIVrIJZFNSwjSUm", album_url: "https://en.wikipedia.org/wiki/Plastic_Hearts#/media/File:Miley_Cyrus_-_Plastic_Hearts.png", genre_id: genres["Pop & Dance"])
song19 = Song.create(title: "Try", artist: "P!nk", youtube_url: "https://youtu.be/N7satb0Zcag?si=dtr2OANd6v3wLjqO", album_url: "https://en.wikipedia.org/wiki/Try_(Pink_song)#/media/File:Try_cover.png", genre_id: genres["Pop & Dance"])
song20 = Song.create(title: "Footloose", artist: "Kenny Loggins", youtube_url: "https://youtu.be/bfp4jUJuR4Y?si=EBbN1UjGc1l8LLxm", album_url: "https://en.wikipedia.org/wiki/Footloose_(song)#/media/File:KennyLooginsFootlooseSingle.jpg", genre_id: genres["Rock"])
song21 = Song.create(title: "Africa", artist: "Toto", youtube_url: "https://youtu.be/1yLNtddTIN8?si=vySjYUlInWntAAOh", album_url: "https://en.wikipedia.org/wiki/Africa_(song)#/media/File:Toto_-_Africa.jpg", genre_id: genres["Rock"])
song22 = Song.create(title: "Take Me To Church", artist: "Hozier", youtube_url: "https://youtu.be/RxJIf9iB780?si=LUpiOpti9aIT-E_h", album_url: "https://en.wikipedia.org/wiki/Take_Me_to_Church#/media/File:Hozier_Take_Me_to_Church.jpg", genre_id: genres["R&B & Soul"])
song23 = Song.create(title: "Have You Ever Seen The Rain", artist: "Rod Stewart", youtube_url: "https://youtu.be/MvYMFQ8-TdY?si=Bo-s0ij5Mvf83n_P", album_url: "https://en.wikipedia.org/wiki/Have_You_Ever_Seen_the_Rain%3F#/media/File:HYESTR-CCR.jpg", genre_id: genres["Rock"])
song24 = Song.create(title: "Chandelier", artist: "Sia", youtube_url: "https://youtu.be/jZLS_kpefuM?si=cqw8PzZ4-AydsCtW", album_url: "https://en.wikipedia.org/wiki/Chandelier_(song)#/media/File:Sia_Chandelier.png", genre_id: genres["Pop & Dance"])
song25 = Song.create(title: "Daddy Issues", artist: "The Neighbourhood", youtube_url: "https://youtu.be/BwNy0kXjVyw?si=XoWPKM0_85szdXiB", album_url: "https://en.wikipedia.org/wiki/Wiped_Out!#/media/File:The_Neighbourhood_-_Wiped_Out.jpg", genre_id: genres["Rock"])
song26 = Song.create(title: "Flowers", artist: "Miley Cyrus", youtube_url: "https://youtu.be/fQemUin8g-I?si=ytZ83dj57Cb0hPF8", album_url: "https://en.wikipedia.org/wiki/Flowers_(Miley_Cyrus_song)#/media/File:Miley_Cyrus_-_Flowers_(digital_single).png", genre_id: genres["Pop & Dance"])
song27 = Song.create(title: "Torn", artist: "Natalie Imbruglia", youtube_url: "https://youtu.be/NogHM5V-vuk?si=teKCdQ9RbuEdcm1p", album_url: "https://en.wikipedia.org/wiki/Torn_(Ednaswap_song)#/media/File:Single_Ednaswap_Torn_Cover.png", genre_id: genres["R&B & Soul"])
song28 = Song.create(title: "Because Of You", artist: "Kelly Clarkson", youtube_url: "https://youtu.be/9SAh14Kt4n8?si=w3RjGZ4oEPzVgfMl", album_url: "https://en.wikipedia.org/wiki/Because_of_You_(Kelly_Clarkson_song)#/media/File:Because_of_You_Single.PNG", genre_id: genres["Pop & Dance"])
song29 = Song.create(title: "Dusk Till Dawn", artist: "ZAYN & Sia", youtube_url: "https://youtu.be/K5w1ujw-gGw?si=g7ApasRXgAGHJLs3", album_url: "https://en.wikipedia.org/wiki/Dusk_Till_Dawn_(Zayn_song)#/media/File:Dusk_Till_Dawn_Zayn_Malik.jpg", genre_id: genres["Pop & Dance"])
song30 = Song.create(title: "Smooth Operator", artist: "Sade", youtube_url: "https://youtu.be/Ba4zPD3DkMw?si=kAE8QPe7j2Ojh5U4", album_url: "https://en.wikipedia.org/wiki/Smooth_Operator#/media/File:Sade_-_Smooth_Operator.png", genre_id: genres["R&B & Soul"])
song31 = Song.create(title: "Beggin'", artist: "Måneskin", youtube_url: "https://youtu.be/TeThp6h1K3w?si=offgDcZwzhiA92A0", album_url: "https://en.wikipedia.org/wiki/M%C3%A5neskin#/media/File:Maneskin_2018.jpg", genre_id: genres["Rock"])
song32 = Song.create(title: "No", artist: "Meghan Trainor", youtube_url: "https://youtu.be/zP3uXydqSEU?si=-ckhZ8nK8WrE1SC7", album_url: "https://en.wikipedia.org/wiki/No_(Meghan_Trainor_song)#/media/File:Meghan_Trainor_-_N%C3%98_(Official_Single_Cover).png", genre_id: genres["Pop & Dance"])
song33 = Song.create(title: "Last Friday Night (T.G.I.F)", artist: "Katy Perry", youtube_url: "https://youtu.be/m3IH5arFaQg?si=kw5gWoJFZoD1LGFa", album_url: "https://en.wikipedia.org/wiki/Last_Friday_Night_(T.G.I.F.)#/media/File:Last_Friday_Night_cover.png", genre_id: genres["Pop & Dance"])
song34 = Song.create(title: "Shut Up and Dance", artist: "WALK THE MOON", youtube_url: "https://youtu.be/X8HUhFSLnl0?si=VIlkb9HoP70K_x_k", album_url: "https://en.wikipedia.org/wiki/Shut_Up_and_Dance_(Walk_the_Moon_song)#/media/File:Walk_the_Moon_-_Shut_Up_and_Dance_(Official_Single_Cover).png", genre_id: genres["Pop & Dance"])
song35 = Song.create(title: "Beautiful Girls", artist: "Sean Kingston", youtube_url: "https://youtu.be/ITtJ-jegSZo?si=QH4WTzGdrBmvaoW9", album_url: "https://en.wikipedia.org/wiki/Beautiful_Girls_(Sean_Kingston_song)#/media/File:Sean_Kingston_Beautiful_Girls.jpg", genre_id: genres["Pop & Dance"])
song36 = Song.create(title: "Smells Like Teen Spirit", artist: "Nirvana", youtube_url: "https://youtu.be/69Wqhhun5_o?si=SYeoGMB_Ly5i3QEC", album_url: "https://en.wikipedia.org/wiki/Smells_Like_Teen_Spirit#/media/File:Smells_Like_Teen_Spirit.jpg", genre_id: genres["Rock"])
song37 = Song.create(title: "I Hate Everything About You", artist: "Three Days Grace", youtube_url: "https://youtu.be/GrD3dDUKxYY?si=k7Sz4By53Sei7ppH", album_url: "https://en.wikipedia.org/wiki/I_Hate_Everything_About_You#/media/File:Three_days_grace_i_hate_everything_about_you.png", genre_id: genres["Rock"])
song38 = Song.create(title: "Summertime Sadness", artist: "Lana Del Rey", youtube_url: "https://youtu.be/RexHuYl7_4c?si=dB6VaT6Hc5tDZgcB", album_url: "https://en.wikipedia.org/wiki/Summertime_Sadness#/media/File:SummertimeSadnessOfficial.png", genre_id: genres["R&B & Soul"])
song39 = Song.create(title: "Back In Black", artist: "AC/DC", youtube_url: "https://youtu.be/rrim6_9VSeM?si=bhVJiQqDjysMRGe7", album_url: "https://en.wikipedia.org/wiki/Back_in_Black#/media/File:ACDC_Back_in_Black.png", genre_id: genres["Rock"])
song40 = Song.create(title: "Stay", artist: "The Kid LAROI, Justin Bieber", youtube_url: "https://youtu.be/mQT0lnB44K8?si=-FSq5Y0BIOTFLE44", album_url: "https://en.wikipedia.org/wiki/Stay_(The_Kid_Laroi_and_Justin_Bieber_song)#/media/File:The_Kid_Laroi_and_Justin_Bieber_-_Stay.png", genre_id: genres["Pop & Dance"])
song41 = Song.create(title: "Making Love Out Of Nothing At All", artist: "Air Supply", youtube_url: "https://youtu.be/93F29FCAQtA?si=lvk-LyRVixoAeI1j", album_url: "https://en.wikipedia.org/wiki/Making_Love_Out_of_Nothing_at_All#/media/File:Making_Love_Out_of_Nothing_at_All.jpg", genre_id: genres["Rock"])
song42 = Song.create(title: "Fast Car", artist: "Luke Combs", youtube_url: "https://youtu.be/st6XCAv0E4M?si=0Je_tO6Kfa1GGa1m", album_url: "https://en.wikipedia.org/wiki/Gettin%27_Old#/media/File:Luke_Combs_-_Gettin'_Old.png", genre_id: genres["R&B & Soul"])
song43 = Song.create(title: "Come As You Are", artist: "Nirvana", youtube_url: "https://youtu.be/9I9c20LHmzY?si=T1pgF9bhwR1a4VOF", album_url: "https://en.wikipedia.org/wiki/Come_as_You_Are_(Nirvana_song)#/media/File:ComeAsYouAre.jpg", genre_id: genres["Rock"])
song44 = Song.create(title: "Carrie", artist: "Europe", youtube_url: "https://youtu.be/oyInf9xuPx8?si=6ZTR3qiPXaWnHHkK", album_url: "https://en.wikipedia.org/wiki/Carrie_(Europe_song)#/media/File:Europe_Carrie_single.jpg", genre_id: genres["Rock"])
song45 = Song.create(title: "Basket Case", artist: "Green Day", youtube_url: "https://youtu.be/_lof1pYtL9Q?si=fpfG8VTckLjSVIMN", album_url: "https://en.wikipedia.org/wiki/Basket_Case_(song)#/media/File:Green_Day_-_Basket_Case_(UK_cover).jpg", genre_id: genres["Rock"])
song46 = Song.create(title: "Wrecking Ball", artist: "Miley Cyrus", youtube_url: "https://youtu.be/S4oQWgTfCFA?si=j1iOYvffCdZUFW-T", album_url: "https://en.wikipedia.org/wiki/Wrecking_Ball_(Miley_Cyrus_song)#/media/File:Miley_Cyrus_-_Wrecking_Ball.jpg", genre_id: genres["Pop & Dance"])
song47 = Song.create(title: "Danger Zone", artist: "Kenny Loggins", youtube_url: "https://youtu.be/CRGbe95EQyI?si=ULExXEstenN0qb9M", album_url: "https://en.wikipedia.org/wiki/Danger_Zone_(song)#/media/File:Loggins_-_Danger_Zone_single_cover.png", genre_id: genres["Rock"])
song48 = Song.create(title: "Baby One More Time", artist: "Britney Spears", youtube_url: "https://youtu.be/nbmVTIYkbOo?si=24TDihOcR0s0PB1o", album_url: "https://en.wikipedia.org/wiki/...Baby_One_More_Time#/media/File:...Baby_One_More_Time_Single.png", genre_id: genres["Pop & Dance"])
song49 = Song.create(title: "Purple Rain", artist: "Prince", youtube_url: "https://youtu.be/OOM6TiWJdps?si=Q016bp5YPy8Y_vH3", album_url: "https://en.wikipedia.org/wiki/Purple_Rain_(album)#/media/File:Princepurplerain.jpg", genre_id: genres["Rock"])
song50 = Song.create(title: "Can't Stop", artist: "Red Hot Chili Peppers", youtube_url: "https://youtu.be/8a-9Sd35HNI?si=-nkw9zDnPjjX3AIy", album_url: "https://en.wikipedia.org/wiki/Can%27t_Stop_(Red_Hot_Chili_Peppers_song)#/media/File:RedHotChiliPeppersCantStop.jpg", genre_id: genres["Rock"])
song51 = Song.create(title: "Down Under", artist: "Men At Work", youtube_url: "https://youtu.be/FDD7O8oNoFI?si=kMyqgvBRN7QJMLHk", album_url: "https://de.wikipedia.org/wiki/Down_Under_(Lied)#/media/Datei:Men_At_Work_-_Down_Under1.jpg", genre_id: genres["Rock"])
song52 = Song.create(title: "White Flag", artist: "Dido", youtube_url: "https://youtu.be/7d5fWYhSbBc?si=MOy7T7pJtF4Q9Udh", album_url: "https://en.wikipedia.org/wiki/White_Flag_(Dido_song)#/media/File:White_Flag_Dido.jpg", genre_id: genres["R&B & Soul"])
song53 = Song.create(title: "Gravity", artist: "John Mayer", youtube_url: "https://youtu.be/53pweVfVwV8?si=4_8-XtfH3a8LDRvs", album_url: "https://en.wikipedia.org/wiki/Gravity_(John_Mayer_song)#/media/File:Johnmayer_gravity.jpg", genre_id: genres["Rock"])
song54 = Song.create(title: "Chasing Cars", artist: "Snow Patrol", youtube_url: "https://youtu.be/rbgiJu7YFvo?si=9tf6ifR45VvQJuOC", album_url: "https://en.wikipedia.org/wiki/Chasing_Cars#/media/File:Chasingcars.jpg", genre_id: genres["Rock"])
song55 = Song.create(title: "golden hour", artist: "JVKE", youtube_url: "https://youtu.be/HZ8kfEsx_u0?si=SufK3MM_QBGWTuR4", album_url: "https://en.wikipedia.org/wiki/Golden_Hour_(song)#/media/File:JVKE_-_Golden_Hour.png", genre_id: genres["Pop & Dance"])
song56 = Song.create(title: "Stairway To Heaven", artist: "Led Zeppelin", youtube_url: "https://youtu.be/x8z6iqeiOIU?si=0Faz6FlJiAWJsaiP", album_url: "https://en.wikipedia.org/wiki/Stairway_to_Heaven#/media/File:Stairway_to_Heaven_by_Led_Zeppelin_US_promotional_single.png", genre_id: genres["Rock"])
song57 = Song.create(title: "Please Please Please", artist: "Sabrina Carpenter", youtube_url: "https://youtu.be/vvv18aT5MoY?si=czx0msAmo_Fhdj6r", album_url: "https://en.wikipedia.org/wiki/Short_n%27_Sweet#/media/File:Short_n'_Sweet_-_Sabrina_Carpenter.png", genre_id: genres["Pop & Dance"])
song58 = Song.create(title: "Somewhere Only We Know", artist: "Keane", youtube_url: "https://youtu.be/7bP_8WOkbUA?si=oiXTQbMwPzYR8HyY", album_url: "https://en.wikipedia.org/wiki/Somewhere_Only_We_Know#/media/File:Keane-SOWK.jpg", genre_id: genres["Rock"])
song59 = Song.create(title: "Holding Out For A Hero", artist: "Bonnie Tyler", youtube_url: "https://youtu.be/Hq5mVt-iozQ?si=X_tdgmvsLr8-RyVm", album_url: "https://en.wikipedia.org/wiki/Holding_Out_for_a_Hero#/media/File:Bonnie_Tyler_Holding_a_Hero.jpg", genre_id: genres["Rock"])
song60 = Song.create(title: "Mr. Jones", artist: "Counting Crows", youtube_url: "https://youtu.be/OD_03DPD8uc?si=fnJa_WgDnnfxyZtc", album_url: "https://en.wikipedia.org/wiki/Mr._Jones_(Counting_Crows_song)#/media/File:Mr._Jones_(Counting_Crows_song)_cover.jpg", genre_id: genres["Rock"])
song61 = Song.create(title: "Teenage Dirtbag", artist: "Wheatus", youtube_url: "https://youtu.be/8lI-Eh0HYVY?si=zeyULIb7DAW97vQZ", album_url: "https://en.wikipedia.org/wiki/Teenage_Dirtbag#/media/File:Teenage_Dirtbag.jpg", genre_id: genres["Rock"])
song62 = Song.create(title: "Never Let Me Down Again", artist: "Depeche Mode", youtube_url: "https://youtu.be/loRtL_tofpY?si=Ctj9aSgNbMbblBg8", album_url: "https://en.wikipedia.org/wiki/Never_Let_Me_Down_Again#/media/File:DepecheModeNeverLetMeDownAgain.jpg", genre_id: genres["Rock"])
song63 = Song.create(title: "When I Look Into Your Eyes", artist: "Firehouse", youtube_url: "https://youtu.be/GNK22zdgi_k?si=mPS4TcRyGedNlG8f", album_url: "https://en.wikipedia.org/wiki/When_I_Look_into_Your_Eyes#/media/File:When_I_Look_Into_Your_Eyes_(FireHouse_single_-_cover_art).jpg", genre_id: genres["Rock"])
song64 = Song.create(title: "(Don't Fear) The Reaper", artist: "Blue Oyster Cult", youtube_url: "https://youtu.be/I5Lccbax1C4?si=U_J_wQi5XBM9qYbi", album_url: "https://en.wikipedia.org/wiki/(Don%27t_Fear)_The_Reaper#/media/File:DontFearTheReaper.jpg", genre_id: genres["Rock"])
song65 = Song.create(title: "Enjoy The Silence", artist: "Depeche Mode", youtube_url: "https://youtu.be/DarhMTUv3Vg?si=pRoBzj20u5AArBrH", album_url: "https://en.wikipedia.org/wiki/Enjoy_the_Silence#/media/File:DepecheModeEnjoyTheSilence.jpg", genre_id: genres["Rock"])
song66 = Song.create(title: "Under The Bridge", artist: "Red Hot Chili Peppers", youtube_url: "https://youtu.be/8-tcdMwKnpQ?si=oy4yrOQglZlVDNuC", album_url: "https://en.wikipedia.org/wiki/Under_the_Bridge#/media/File:UndertheBridge.jpg", genre_id: genres["Rock"])
song67 = Song.create(title: "Hungry Eyes", artist: "Eric Carmen", youtube_url: "https://youtu.be/svjnabQ58EQ?si=CE443-eYWOexlcKF", album_url: "https://en.wikipedia.org/wiki/Hungry_Eyes#/media/File:Hungry_Eyes.jpg", genre_id: genres["R&B & Soul"])
song68 = Song.create(title: "Sweet Dreams", artist: "Eurythmics", youtube_url: "https://youtu.be/sYSBbp1UFT4?si=LAmWXotdYLgDQreI", album_url: "https://en.wikipedia.org/wiki/Sweet_Dreams_(Are_Made_of_This)#/media/File:Eurythmics_SDAMOT.jpg", genre_id: genres["Rock"])
song69 = Song.create(title: "Islands In the Stream", artist: "Dolly Parton, Kenny Rogers", youtube_url: "https://youtu.be/uObstcmJeLw?si=HCHhBeG2NbOqc_k1", album_url: "https://en.wikipedia.org/wiki/Islands_in_the_Stream_(song)#/media/File:Krdpislands.jpg", genre_id: genres["R&B & Soul"])
song70 = Song.create(title: "Calm Down", artist: "Rema, Selena Gomez", youtube_url: "https://youtu.be/W50sgQV1pl0?si=gx-PGtoQ9aIE6ZGr", album_url: "https://en.wikipedia.org/wiki/Calm_Down_(Rema_song)#/media/File:Rema_-_Calm_Down.png", genre_id: genres["Pop & Dance"])
song71 = Song.create(title: "My Boo", artist: "Usher", youtube_url: "https://youtu.be/kQma-Foa9Hw?si=qZJKknVb-kLuYu8F", album_url: "https://en.wikipedia.org/wiki/My_Boo_(Usher_and_Alicia_Keys_song)#/media/File:Usher_-_My_Boo.png", genre_id: genres["R&B & Soul"])
song72 = Song.create(title: "Closer", artist: "The Chainsmokers", youtube_url: "https://youtu.be/OGP499ko5EQ?si=JHcq0sAGHFpq6Jqo", album_url: "https://en.wikipedia.org/wiki/Closer_(The_Chainsmokers_song)#/media/File:Closer_(featuring_Halsey)_(Official_Single_Cover)_by_The_Chainsmokers.png", genre_id: genres["Pop & Dance"])
song73 = Song.create(title: "Hall Of Fame", artist: "The Script", youtube_url: "https://youtu.be/rPlwqDjzJ14?si=hwSNdjw7fCNgQCBK", album_url: "https://en.wikipedia.org/wiki/Hall_of_Fame_(song)#/media/File:Halloffamethescript.jpg", genre_id: genres["Rock"])
song74 = Song.create(title: "undressed", artist: "sombr", youtube_url: "https://youtu.be/ru7PYYCLc1k?si=Pv9JE0ipCMNp29CA", album_url: "https://en.wikipedia.org/wiki/Undressed_(Sombr_song)#/media/File:Official_single_cover_of_%22Undressed%22_by_Sombr.jpeg", genre_id: genres["Hip-Hop & Rap"])
song75 = Song.create(title: "Rude", artist: "MAGIC!", youtube_url: "https://youtu.be/AUnLniHkiCM?si=QHqKJLKcD7q7tDBm", album_url: "https://en.wikipedia.org/wiki/Rude_(song)#/media/File:Magic!_-_Rude.png", genre_id: genres["Pop & Dance"])
song76 = Song.create(title: "hot girl bummer", artist: "blackbear", youtube_url: "https://youtu.be/IjCOt0fYRM4?si=Cqu-Pw52OyDjM2WV", album_url: "https://en.wikipedia.org/wiki/Hot_Girl_Bummer#/media/File:Blackbear_-_Hot_Girl_Bummer.png", genre_id: genres["Hip-Hop & Rap"])
song77 = Song.create(title: "Sweet Emotion", artist: "Aerosmith", youtube_url: "https://youtu.be/Q8_Ohrc4IfE?si=j045POGNcz98ieva", album_url: "https://en.wikipedia.org/wiki/Sweet_Emotion#/media/File:Aerosmith_Sweet_Emotions.jpg", genre_id: genres["Rock"])
song78 = Song.create(title: "I Fought the Law", artist: "The Clash", youtube_url: "https://youtu.be/MYV4KumFROs?si=u9FR6w8jV0-ZNZVI", album_url: "https://en.wikipedia.org/wiki/The_Clash_(album)#/media/File:The_Clash_UK.jpg", genre_id: genres["Rock"])
song79 = Song.create(title: "Burning heart", artist: "Survivor", youtube_url: "https://youtu.be/7WhjoreV3hw?si=NgRKKi2QScnVVwaA", album_url: "https://en.wikipedia.org/wiki/Burning_Heart_(song)#/media/File:Burning_heart.jpg", genre_id: genres["Rock"])
song80 = Song.create(title: "Cecilia", artist: "Simon & Garfunkel", youtube_url: "https://youtu.be/tBOhB89dPw0?si=luG3dL8lz-n9nJlh", album_url: "https://en.wikipedia.org/wiki/Cecilia_(Simon_%26_Garfunkel_song)#/media/File:Cecilia45.jpg", genre_id: genres["Rock"])
song81 = Song.create(title: "Wonderwall", artist: "Bring Me The Horizon", youtube_url: "https://youtu.be/dRFXRf3vtV4?si=ENBAjeBRX5tLjQ_B", album_url: "https://en.wikipedia.org/wiki/Bring_Me_the_Horizon_discography#/media/File:2023_Rock_im_Park_-_Bring_Me_The_Horizon_-_by_2eight_-_7DS4796.jpg", genre_id: genres["Rock"])
song82 = Song.create(title: "Start Me Up", artist: "The Rolling Stones", youtube_url: "https://youtu.be/zjrBFG0Sfks?si=W6dAG5ldFiQrgtya", album_url: "https://en.wikipedia.org/wiki/Start_Me_Up#/media/File:RollStones-Single1981_StartMeUp.jpg", genre_id: genres["Rock"])
song83 = Song.create(title: "Total Eclipse of the Heart", artist: "Bonnie Tyler", youtube_url: "https://youtu.be/xtrWOjqHUa0?si=nHkrTNXkSeD-PBHo", album_url: "https://en.wikipedia.org/wiki/Total_Eclipse_of_the_Heart#/media/File:Total_Eclipse_of_the_Heart_-_single_cover.jpg", genre_id: genres["Rock"])
song84 = Song.create(title: "Ghost Riders in the Sky", artist: "Johnny Cash", youtube_url: "https://youtu.be/BGEsGmxR7JQ?si=R0gNElLmG7sAKdcN", album_url: "https://en.wikipedia.org/wiki/Silver_(Johnny_Cash_album)#/media/File:JohnnyCashSilver.jpg", genre_id: genres["Rock"])
song85 = Song.create(title: "Tomorrow", artist: "Silverchair", youtube_url: "https://youtu.be/y8ZaBMB0U6g?si=qAiu8OZ0gHqXROwS", album_url: "https://en.wikipedia.org/wiki/Tomorrow_(Silverchair_song)#/media/File:TomorrowEuCover.JPG", genre_id: genres["Rock"])
song86 = Song.create(title: "EDGING", artist: "blink-182", youtube_url: "https://youtu.be/SWu9q1_z6To?si=_PBBJ1PBzGdsG9xT", album_url: "https://en.wikipedia.org/wiki/Edging_(song)#/media/File:Blink-182_-_Edging.png", genre_id: genres["Rock"])
song87 = Song.create(title: "TAKE ME IN", artist: "blink-182", youtube_url: "https://youtu.be/tnVMdc94OnI?si=vjUw1L1fSC90b8YC", album_url: "https://en.wikipedia.org/wiki/Blink-182_(album)#/media/File:Blink-182_-_Blink-182_cover.jpg", genre_id: genres["Rock"])
song88 = Song.create(title: "Sexy to Someone", artist: "Clairo", youtube_url: "https://youtu.be/jEg4vL_gRAQ?si=2Qlse006u3McOgSl", album_url: "https://en.wikipedia.org/wiki/Charm_(Clairo_album)#/media/File:Clairo_-_Charm.png", genre_id: genres["Pop & Dance"])
song89 = Song.create(title: "Lose Yourself", artist: "Eminem", youtube_url: "https://www.youtube.com/watch?v=tR1ECf4sEpw", album_url: "https://en.wikipedia.org/wiki/Lose_Yourself#/media/File:Lose_Yourself.jpg", genre_id: genres["Hip-Hop & Rap"])
song90 = Song.create(title: "Not Like Us", artist: "Kendrick Lamar", youtube_url: "https://www.youtube.com/watch?v=d-9W8MoAM3M", album_url: "https://en.wikipedia.org/wiki/Not_Like_Us#/media/File:Kendrick_Lamar_-_Not_Like_Us.png", genre_id: genres["Hip-Hop & Rap"])
song91 = Song.create(title: "Straight Outta Compton", artist: "N.W.A.", youtube_url: "https://www.youtube.com/watch?v=pcqhWPXmx9Y", album_url: "https://en.wikipedia.org/wiki/Straight_Outta_Compton#/media/File:StraightOuttaComptonN.W.A..jpg", genre_id: genres["Hip-Hop & Rap"])
song92 = Song.create(title: "Super Freaky Girl", artist: "Nicki Minaj", youtube_url: "https://www.youtube.com/watch?v=nLfsrNvclbg", album_url: "https://en.wikipedia.org/wiki/Super_Freaky_Girl#/media/File:Nicki_Minaj_-_Super_Freaky_Girl.png", genre_id: genres["Hip-Hop & Rap"])

# other seed items

# user feedback
puts "seeded #{Genre.count} genres and #{Song.count} songs."
